package hikaxprogo

const (
	Session_Capabilities = "/ISAPI/Security/sessionLogin/capabilities?username="
	Session_Login        = "/ISAPI/Security/sessionLogin"
	Alarm_Disarm         = "/ISAPI/SecurityCP/control/disarm/0xffffffff"
	Alarm_ArmAway        = "/ISAPI/SecurityCP/control/arm/0xffffffff?ways=away"
	Alarm_ArmHome        = "/ISAPI/SecurityCP/control/arm/0xffffffff?ways=stay"
	SubSystemStatus      = "/ISAPI/SecurityCP/status/subSystems"
	AlertStream          = "/ISAPI/Event/notification/alertStream"
	DetectorConfig       = "/ISAPI/SecurityCP/BasicParam/DetectorCfg"
	DetectorConfigCap    = "/ISAPI/SecurityCP/BasicParam/DetectorCfg/capabilities"
	Caps                 = "/ISAPI/SecurityCP/capabilities"
	CheckResultCap       = "/ISAPI/SecurityCP/CheckResult/capabilities"
	CheckResult          = "/ISAPI/SecurityCP/CheckResult"
	ConfCap              = "/ISAPI/SecurityCP/Configuration/capabilities"
	DeviceTime           = "/ISAPI/SecurityCP/Configuration/deviceTime"
	EventRecordCap       = "/ISAPI/SecurityCP/Configuration/eventRecord/channels/2/capabilities"
	EventRecord          = "/ISAPI/SecurityCP/Configuration/eventRecord/channels/1"
	FaultCheck           = "/ISAPI/SecurityCP/Configuration/faultCheckCfg"
	GlassBreakDetector   = "/ISAPI/SecurityCP/Configuration/glassBreakDetector/zone/5"
	MagneticContact      = "/ISAPI/SecurityCP/Configuration/magneticContact/zone/0"
	PublicSubSystem      = "/ISAPI/SecurityCP/Configuration/publicSubSys"
	ZonesCap             = "/ISAPI/SecurityCP/Configuration/zones/capabilities"
	Zones                = "/ISAPI/SecurityCP/Configuration/zones/"
	ArmStatus            = "/ISAPI/SecurityCP/status/armStatus"
	StatusCap            = "/ISAPI/SecurityCP/status/capabilities"
	HostStatus           = "/ISAPI/SecurityCP/status/host"
	PeripheralsStatus    = "/ISAPI/SecurityCP/status/exDevStatus"
	ZoneStatus           = "/ISAPI/SecurityCP/status/zones?format=xml"
	BypassZone           = "/ISAPI/SecurityCP/control/bypass/"
	RecoverBypassZone    = "/ISAPI/SecurityCP/control/Recoverbypass/"
	InterfaceInfo        = "/ISAPI/System/Network/interfaces"
	AreaArmStatus        = "/ISAPI/SecurityCP/status/armStatus"
)
